apiVersion: v1
kind: Service
metadata:
  name: apiservice
spec:
  type: ClusterIP
  ports:
    - port: 80 #port d'écoute du service
      targetPort: 8501 # port des pods vers lequel le service redirige les requêtes
  selector:
    app: pod-app